module udp_core_sgmii #(

parameter DATAWIDTH = 16,
parameter ADC_CHANEL = 1
    )(
    // System Interface
    input         clk_udp,            // System clock (125MHz), for other modules
    input         rst_n,              // Active-low reset (asynchronous)

    // Configuration Interface
    input  [31:0] board_ip,
    input  [31:0] des_ip,
    input  [15:0] tx_data_num,
    input         udp_tx_enable,
    input  [15:0] board_port,
    input  [15:0] des_port,

    // FIFO Interface
    input  [ADC_CHANEL*DATAWIDTH-1:0] tx_udp_data,
    (* MARK_DEBUG="true" *)output        tx_req,
    input         DataAccept,       // Pulse signal (1-cycle)

    // SGMII Interface (directly to PHY)
    input  wire   phy_sgmii_rx_p,
    input  wire   phy_sgmii_rx_n,
    output wire   phy_sgmii_tx_p,
    output wire   phy_sgmii_tx_n,
    input  wire   phy_sgmii_clk_p,   // 625MHz ref clock from PHY (differential)
    input  wire   phy_sgmii_clk_n,
    output wire   phy_reset_n,        // PHY hardware reset (active-low)

    // Clock/Reset Output (from PCS/PMA, for external use)
    output wire   phy_gmii_clk,       // 125MHz GMII clock generated by PCS/PMA
    output wire   phy_gmii_rst,       // GMII reset (active-high, sync to phy_gmii_clk)
    output wire   phy_gmii_clk_en,    // GMII clock enable (always 1 at 1Gbps)

    // Status Interface
    output        udp_tx_done,        // UDP transmission complete
    output        udp_busy,           // UDP core busy signal
    output [15:0] sgmii_status_vector // PCS/PMA status vector
);

    // =====================================================================
    // Internal Signals
    // =====================================================================
    wire          phy_gmii_clk_int;
    wire          phy_gmii_rst_int;
    wire          phy_gmii_clk_en_int;

    (* MARK_DEBUG="true" *) wire          gmii_tx_en;
    (* MARK_DEBUG="true" *) wire  [7:0]   gmii_txd;
    wire          gmii_tx_er;

    // RX signals (from PCS/PMA, unused in TX-only design)
    wire  [7:0]   gmii_rxd;
    wire          gmii_rx_dv;
    wire          gmii_rx_er;

    (* MARK_DEBUG="true" *) reg           internal_tx_start_en_pulse;
    wire          data_req;
    reg   [ADC_CHANEL*DATAWIDTH-1:0]  udp_tx_data_mux;

    // UDP State Machine
    reg           udp_busy_state;
    localparam S_IDLE    = 1'b0;
    localparam S_SENDING = 1'b1;

    // MAC Address Parameters
    localparam BOARD_MAC = 48'h12_34_56_78_9a_bc;
    localparam DES_MAC   = 48'hff_ff_ff_ff_ff_ff;

    // =====================================================================
    // Reset Synchronizer (on clk_udp domain, same as original udp_core)
    // =====================================================================
    reg rst_s1_udp, rst_s2_udp;
    wire udp_rst_n_sync;

    always @(posedge clk_udp or negedge rst_n) begin
        if (!rst_n) begin
            rst_s1_udp <= 1'b0;
            rst_s2_udp <= 1'b0;
        end else begin
            rst_s1_udp <= 1'b1;
            rst_s2_udp <= rst_s1_udp;
        end
    end
    assign udp_rst_n_sync = rst_s2_udp;

    // =====================================================================
    // Clock/Reset Outputs
    // =====================================================================
    assign phy_gmii_clk    = phy_gmii_clk_int;
    assign phy_gmii_rst    = phy_gmii_rst_int;
    assign phy_gmii_clk_en = phy_gmii_clk_en_int;

    // Internal active-low reset derived from PCS/PMA (sync to phy_gmii_clk_int)
    wire internal_rst_n = ~phy_gmii_rst_int;

    // PHY hardware reset (directly from system reset)
    assign phy_reset_n = rst_n;

    // GMII TX error (not used, tie low)
    assign gmii_tx_er = 1'b0;

    // =====================================================================
    // PCS/PMA Status Vector
    // =====================================================================
    wire [15:0] pcspma_status_vector;
    assign sgmii_status_vector = pcspma_status_vector;

    wire pcspma_status_link_status              = pcspma_status_vector[0];
    wire pcspma_status_link_synchronization     = pcspma_status_vector[1];
    wire pcspma_status_rudi_c                   = pcspma_status_vector[2];
    wire pcspma_status_rudi_i                   = pcspma_status_vector[3];
    wire pcspma_status_rudi_invalid             = pcspma_status_vector[4];
    wire pcspma_status_rxdisperr                = pcspma_status_vector[5];
    wire pcspma_status_rxnotintable             = pcspma_status_vector[6];
    wire pcspma_status_phy_link_status          = pcspma_status_vector[7];
    wire [1:0] pcspma_status_remote_fault_encdg = pcspma_status_vector[9:8];
    wire [1:0] pcspma_status_speed              = pcspma_status_vector[11:10];
    wire pcspma_status_duplex                   = pcspma_status_vector[12];
    wire pcspma_status_remote_fault             = pcspma_status_vector[13];
    wire [1:0] pcspma_status_pause              = pcspma_status_vector[15:14];

    // =====================================================================
    // PCS/PMA Configuration Vectors
    // =====================================================================
    wire [4:0] pcspma_config_vector;

    assign pcspma_config_vector[4] = 1'b1; // autonegotiation enable
    assign pcspma_config_vector[3] = 1'b0; // isolate
    assign pcspma_config_vector[2] = 1'b0; // power down
    assign pcspma_config_vector[1] = 1'b0; // loopback enable
    assign pcspma_config_vector[0] = 1'b0; // unidirectional enable

    wire [15:0] pcspma_an_config_vector;

    assign pcspma_an_config_vector[15]    = 1'b1;    // SGMII link status
    assign pcspma_an_config_vector[14]    = 1'b1;    // SGMII Acknowledge
    assign pcspma_an_config_vector[13:12] = 2'b01;   // full duplex
    assign pcspma_an_config_vector[11:10] = 2'b10;   // SGMII speed (1000Mbps)
    assign pcspma_an_config_vector[9]     = 1'b0;    // reserved
    assign pcspma_an_config_vector[8:7]   = 2'b00;   // pause frames - SGMII reserved
    assign pcspma_an_config_vector[6]     = 1'b0;    // reserved
    assign pcspma_an_config_vector[5]     = 1'b0;    // full duplex - SGMII reserved
    assign pcspma_an_config_vector[4:1]   = 4'b0000; // reserved
    assign pcspma_an_config_vector[0]     = 1'b1;    // SGMII

    // =====================================================================
    // UDP Busy Status
    // =====================================================================
    assign udp_busy = (udp_busy_state == S_SENDING);

    // =====================================================================
    // External Data Request
    // =====================================================================
    assign tx_req = data_req;

    // =====================================================================
    // Data MUX
    // =====================================================================
    always @(*) begin
        udp_tx_data_mux = tx_udp_data;
    end

    // =====================================================================
    // UDP Transmission State Machine
    // Clocked by phy_gmii_clk_int (125MHz from PCS/PMA)
    // =====================================================================
    always @(posedge phy_gmii_clk_int or negedge internal_rst_n) begin
        if (!internal_rst_n) begin
            udp_busy_state <= S_IDLE;
            internal_tx_start_en_pulse <= 1'b0;
        end else begin
            internal_tx_start_en_pulse <= 1'b0; // Default

            case(udp_busy_state)
                S_IDLE: begin
                    if (udp_tx_enable) begin
                        internal_tx_start_en_pulse <= 1'b1;
                        udp_busy_state <= S_SENDING;
                    end
                end

                S_SENDING: begin
                    if (udp_tx_done) begin
                        udp_busy_state <= S_IDLE;
                    end
                end

                default: udp_busy_state <= S_IDLE;
            endcase
        end
    end

    // =====================================================================
    // Module Instantiations
    // =====================================================================

    //---------------------------------------------------------------------
    // Xilinx PCS/PMA IP (gig_ethernet_pcs_pma_0)
    // Handles SGMII serialization/deserialization and auto-negotiation
    // NOTE: Generate this IP in Vivado with SGMII mode, shared logic in core
    //---------------------------------------------------------------------
    gig_ethernet_pcs_pma_0 u_eth_pcspma (
        // SGMII differential pairs
        .txp                    (phy_sgmii_tx_p),
        .txn                    (phy_sgmii_tx_n),
        .rxp                    (phy_sgmii_rx_p),
        .rxn                    (phy_sgmii_rx_n),

        // 625MHz reference clock from PHY (differential)
        .refclk625_p            (phy_sgmii_clk_p),
        .refclk625_n            (phy_sgmii_clk_n),

        // Async reset (active-high, from synchronized system reset)
        .reset                  (~udp_rst_n_sync),

        // Clock and reset outputs
        .clk125_out             (phy_gmii_clk_int),
        .clk625_out             (),
        .clk312_out             (),
        .rst_125_out            (phy_gmii_rst_int),
        .idelay_rdy_out         (),
        .mmcm_locked_out        (),

        // MAC clocking
        .sgmii_clk_r            (),
        .sgmii_clk_f            (),
        .sgmii_clk_en           (phy_gmii_clk_en_int),

        // Speed control
        .speed_is_10_100        (pcspma_status_speed != 2'b10),
        .speed_is_100           (pcspma_status_speed == 2'b01),

        // Internal GMII (directly connected to udp module)
        .gmii_txd               (gmii_txd),
        .gmii_tx_en             (gmii_tx_en),
        .gmii_tx_er             (gmii_tx_er),
        .gmii_rxd               (gmii_rxd),
        .gmii_rx_dv             (gmii_rx_dv),
        .gmii_rx_er             (gmii_rx_er),
        .gmii_isolate           (),

        // Configuration
        .configuration_vector   (pcspma_config_vector),

        .an_interrupt           (),
        .an_adv_config_vector   (pcspma_an_config_vector),
        .an_restart_config      (1'b0),

        // Status
        .status_vector          (pcspma_status_vector),
        .signal_detect          (1'b1)
    );

    //---------------------------------------------------------------------
    // UDP TX Module
    // Uses phy_gmii_clk_int as GMII TX clock (from PCS/PMA)
    //---------------------------------------------------------------------
    udp #(
        .ADC_CHANEL(ADC_CHANEL),
        .DATAWIDTH(DATAWIDTH)
    ) u_udp (
        .BOARD_MAC     (BOARD_MAC),
        .BOARD_IP      (board_ip),
        .BOARD_PORT    (board_port),
        .DES_MAC       (DES_MAC),
        .DES_IP        (des_ip),
        .DES_PORT      (des_port),
        .rst_n         (internal_rst_n),
        .gmii_tx_clk   (phy_gmii_clk_int),
        .gmii_tx_en    (gmii_tx_en),
        .gmii_txd      (gmii_txd),
        .tx_start_en   (internal_tx_start_en_pulse),
        .tx_data       (udp_tx_data_mux),
        .tx_byte_num   (tx_data_num),
        .tx_done       (udp_tx_done),
        .tx_req        (data_req)
    );

endmodule
