# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/RISCV_Project/fpga/project/Tiny_FPGA/.Xil/Vivado-25572-DESKTOP-98PI6EB/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tfgg484-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/FIFO/prim_fifo_async.v
      rt::read_verilog -include D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core {
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/ADC_UDP_Top.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/Baseline_Volt_Cal.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/perips/I2C_ctrl.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/perips/SPI_master.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/perips/SPI_warpper.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/adc_core.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/clint.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/crc32_d8.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/csr_reg.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/divider.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/exu.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/exu_alu_datapath.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/exu_commit.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/exu_dispatch.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/exu_mem.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/exu_muldiv.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/utils/full_handshake_rx.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/utils/full_handshake_tx.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/utils/gen_buf.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/utils/gen_dff.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/utils/gen_ram.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/perips/gpio.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/gpr_reg.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/perips/i2c_master.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/idu.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/idu_exu.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/ifu.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/ifu_idu.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/debug/jtag_dm.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/debug/jtag_driver.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/debug/jtag_top.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/pipe_ctrl.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/FIFO/prim_flop.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/FIFO/prim_flop_2sync.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/perips/ram.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/reset_generator.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/rgmii_tx.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/sys_bus/rib.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/rib_wr.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/perips/rom.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/rst_ctrl.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/perips/timer.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/core/tinyriscv_core.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/top_ctrl.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/perips/uart.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/udp.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/udp_core.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/ADC_UDP_TOP/udp_tx.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/utils/vld_rdy.v
      D:/RISCV_Project/fpga/project/Tiny_FPGA/Tiny_FPGA.srcs/sources_1/imports/rtl/top/tinyriscv_soc_top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top tinyriscv_soc_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/RISCV_Project/fpga/project/Tiny_FPGA/.Xil/Vivado-25572-DESKTOP-98PI6EB/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
